# @package _global_
defaults:
  - override /interpreter: python
  - override /solver: mlebench/greedy
  - override /task: mlebench/nomad2018-predict-transparent-conductors
  - override /solver/client@solver.operators.analyze.llm.client: gigachat_llm
  - override /solver/client@solver.operators.debug.llm.client: gigachat_llm
  - override /solver/client@solver.operators.draft.llm.client: gigachat_llm
  - override /solver/client@solver.operators.improve.llm.client: gigachat_llm

metadata:
  git_issue_id: example # Ideally, this should be a number fetched from github issue when running an actual experiment.

solver:
  step_limit: 5