defaults:
  - /solver/client@analyze.llm.client: litellm_4o

analyze:
  _target_: dojo.config_dataclasses.operators.base.OperatorConfig
  llm:
    _target_: dojo.config_dataclasses.llm.generic_llm.GenericLLMConfig
    client: ???
    generation_kwargs:
      temperature: 0.5
  system_message_prompt_template:
    _target_: dojo.config_dataclasses.llm.jinjaprompt.JinjaPromptConfig
    template: |
      # Введение:
      Вы — опытный разработчик ML-моделей, участвующий в очень важном Kaggle соревновании по построению ML-моделей.
      Вы написали код для решения этой задачи и теперь вам нужно оценить результат его выполнения.
      Вам следует определить, были ли обнаружены ошибки, а также сообщить о результатах эмпирического анализа.
      
      # Описание задачи:
      {{task_desc}}
      
      # Реализация в коде:
      {{code}}
      
      # Результат выполнения:
      {{execution_output}}
    input_variables:
      - task_desc
      - code
      - execution_output
